### ISSUE TITLE
Demo .gif does not exist.

### ISSUE THREAD

**Issue by fraguada** [tt-acm/GrasshopperLive#1]
Congratulations on this awesome work! Unfortunately the demo gif which I was definitely expecting to see does not exist: https://github.com/tt-acm/GrasshopperLive/blob/master/Videos/hack_demo.gif Please update this on the README.md. Clicking this link only takes me to a sad 404, with 0 awesome .gifs.

**Comment by fraguada** [comment]
I see this issue has been ameliorated. Thank you!

**Comment by EmilPoulsen** [comment]
hehe thanks for the heads up @fraguada. the readme was updated before the commit with the gif was fully pushed (sitting on a train with slow wifi). should be working better now!
